### ISSUE TITLE
Loadout: Apply to Single Unit provides wrong UI

### ISSUE THREAD

**Issue by Garfield0003** [johnb432/Zeus-Additions#1]
In the current build of the mod on Steam, the module will show the "Spawn Ammo Resupply Crate" UI.

No action is taken when complete

**Comment by johnb432** [comment]
I can't seem to reproduce - if you can, can you send the rpt log?

**Comment by johnb432** [comment]
I have noticed a minor issue in the script, so it might not occur anymore when I update it.

**Comment by Garfield0003** [comment]
Sorry, hadn't been able to respond on this, however I can say that it doesn't happen any more following the update.
Thanks
