### ISSUE TITLE
Create ACE Medical Injuries Not Working

### ISSUE THREAD

**Issue by MAJThomasASOT** [johnb432/Zeus-Additions#29]
Hey mate, 

Since the last ACE, CBA and KAM updates, the create ace medical injuries are not working. 

It simply doesn't add the damage at all when placed on the units. 

I imagine you'll be looking into an update since ACE and CBA updated but thought I'd still report this. 

Happy to do further testing if required.

**Comment by johnb432** [comment]
I am aware that some things are broken. However, it might be some time before I get around to fixing it.

**Comment by johnb432** [comment]
@MAJThomasASOT I have updated the mod. The issue is fixed, although if you encounter problems you can reopen this issue.
