### ISSUE TITLE
Suggestion: Details about ACE Injury

### ISSUE THREAD

**Issue by Garfield0003** [johnb432/Zeus-Additions#3]
Currently on the mod, there is no detail as to what an injury of 0.5 is, and how much worse is a injury with a 5.
If possible, can you add some context so a light wound is <= 0.25, medium <= 0.75, heavy is >0.75 etc.

Otherwise it is just a case of trial and error.
And yes, the injury type may impact this as well, but it is just to provide some guidance.

**Comment by johnb432** [comment]
Tbh this module is very wonky. I agree with you, 0.5 means absolutely nothing as there are no values people can refer to.

At this point I think I would have to rework the module pretty heavily in order to make it work well. But as a temporary solution adding something to the tooltip would be best.

**Comment by johnb432** [comment]
Module has been fully reworked, will be releasing the update shortly.

**Comment by johnb432** [comment]
Closed with new module release.
